interface IncidentClosureReportProps {
  vehicleNumber: string
  incidentId: string
  subscriberId: string
  subscriberName: string
  dateGenerated: string
  reporterName: string
  reporterPhone: string
  dateOfReporting: string
  incidentType: string
  incidentSummary: string
  location: {
    roadName?: string
    area?: string
    city?: string
    state?: string
    pin?: string
  }
  resolutionOpinion?: string
  closureDate: string
  assignedLawyer?: string
  lawyerSpecialization?: string
  authorityInvolved?: string
  finalOutcome: string
  moneySaved?: string
  timeSaved?: string
  closureOutcome: string
  durationDays: number
  slaStatus: string
  documentsFiledCount: number
  closingNotes?: string
}

/* ── Shared sub-components ── */

function SectionCard({
  title,
  icon,
  iconBg = 'bg-stone-100',
  children,
}: {
  title: string
  icon: React.ReactNode
  iconBg?: string
  children: React.ReactNode
}) {
  return (
    <div className="bg-white border border-stone-200 rounded-xl overflow-hidden">
      <div className="flex items-center gap-2 px-8 py-4 border-b border-stone-100 bg-white">
        <span className={`w-10 h-10 rounded-lg flex items-center justify-center ${iconBg}`}>{icon}</span>
        <h3 className="text-[14pt] font-display font-extrabold text-emerald-700 tracking-tight">
          {title}
        </h3>
      </div>
      <div className="px-8 py-6 bg-stone-50/60">{children}</div>
    </div>
  )
}

function LabelValue({
  label,
  value,
  mono,
  large,
}: {
  label: string
  value: string
  mono?: boolean
  large?: boolean
}) {
  return (
    <div>
      <p className="text-[8.5pt] font-semibold text-stone-400 uppercase tracking-wider mb-1">
        {label}
      </p>
      <p className={`font-medium text-stone-800 leading-snug ${mono ? 'font-mono' : ''} ${large ? 'text-[13pt]' : 'text-[11pt]'}`}>
        {value}
      </p>
    </div>
  )
}

function PageHeader({ subtitle }: { subtitle: string }) {
  return (
    <div className="flex items-center justify-between px-10 py-4 border-b border-stone-200 bg-white">
      <img src="/lots247-logo.png" alt="LOTS247" className="h-6 w-auto" />
      <div className="text-right">
        <p className="text-[9pt] font-display font-semibold text-stone-700">Incident Closure Report</p>
        <p className="text-[8pt] font-mono text-stone-400 mt-px">{subtitle}</p>
      </div>
    </div>
  )
}

function PageFooter({ page, total }: { page: number; total: number }) {
  return (
    <div className="px-10 py-3 border-t border-stone-200 bg-white flex items-center text-[8pt] text-stone-400 gap-3">
      <span>Page {page} of {total}</span>
      <span className="text-stone-300">|</span>
      <span>Generated by LOTS247</span>
    </div>
  )
}

/* ── SVG icons ── */

const icons = {
  fileText: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
    </svg>
  ),
  checkCircle: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>
  ),
  shield: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75 11.25 15 15 9.75m-3-7.036A11.959 11.959 0 0 1 3.598 6 11.99 11.99 0 0 0 3 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285Z" />
    </svg>
  ),
  mapPin: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
      <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z" />
    </svg>
  ),
}

/* ── Report: 3 A4 pages ── */

export default function IncidentClosureReport(
  props: IncidentClosureReportProps
) {
  const sub = `${props.incidentId} · ${props.vehicleNumber}`

  return (
    <div
      id="incident-closure-report"
      style={{ fontFamily: '"DM Sans", system-ui, sans-serif' }}
    >
      {/* ════════════ PAGE 1: COVER ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col overflow-hidden">
        {/* Hero image with wave */}
        <div className="w-full h-[38%] flex-shrink-0">
          <img src="/report-cover-bg.png" alt="" className="w-full h-full object-cover object-top" />
        </div>

        {/* Content below wave */}
        <div className="flex-1 flex flex-col items-center px-14 text-center">
          {/* Logo */}
          <div className="pt-6 pb-4">
            <img src="/lots247-logo.png" alt="LOTS247" className="h-10 w-auto mx-auto" />
          </div>

          {/* Title */}
          <h1 className="text-[26pt] font-display font-bold text-stone-900 tracking-tight leading-tight">
            Incident Closure
          </h1>
          <h1 className="text-[26pt] font-display font-bold text-stone-900 tracking-tight leading-tight mb-6">
            Report
          </h1>

          {/* Key identifiers card */}
          <div className="w-full max-w-sm bg-white border border-stone-200 rounded-xl overflow-hidden mb-10">
            <div className="flex border-b border-stone-200">
              <div className="flex-1 px-6 py-5 border-r border-stone-200 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Incident ID</p>
                <p className="text-[16pt] font-mono font-bold text-stone-900">{props.incidentId}</p>
              </div>
              <div className="flex-1 px-6 py-5 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Vehicle No.</p>
                <p className="text-[16pt] font-mono font-bold text-stone-900">{props.vehicleNumber}</p>
              </div>
            </div>
            <div className="px-6 py-3 bg-stone-50">
              <div className="flex items-center justify-center gap-3">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
                <span className="text-[11pt] font-medium text-stone-600">{props.incidentType}</span>
                <span className="text-stone-300 mx-1">&middot;</span>
                <span className="text-[11pt] font-semibold text-emerald-600">{props.finalOutcome}</span>
              </div>
            </div>
          </div>

          {/* Details grid */}
          <div className="w-full max-w-md">
            <div className="grid grid-cols-3 gap-x-8 text-left">
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Subscriber</p>
                <p className="text-[13pt] font-bold text-stone-900">{props.subscriberName}</p>
                <p className="text-[10pt] font-mono text-stone-500 mt-1">{props.subscriberId}</p>
              </div>
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Reporter</p>
                <p className="text-[13pt] font-bold text-stone-900">{props.reporterName}</p>
                <p className="text-[10pt] font-mono text-stone-500 mt-1">{props.reporterPhone}</p>
              </div>
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Date Generated</p>
                <p className="text-[13pt] font-bold text-stone-900">{props.dateGenerated}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="h-1.5 bg-emerald-600" />
        <PageFooter page={1} total={3} />
      </div>

      {/* ════════════ PAGE 2: INCIDENT + RESOLUTION ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader subtitle={sub} />

        <div className="flex-1 px-10 py-8 flex flex-col gap-6">
          <div className="flex-1 bg-white border border-stone-200 rounded-xl overflow-hidden flex flex-col">
            <div className="flex items-center gap-2 px-8 py-5 border-b border-stone-100 bg-white">
              <span className="w-10 h-10 rounded-lg flex items-center justify-center bg-emerald-50">{icons.fileText}</span>
              <h3 className="text-[16pt] font-display font-extrabold text-emerald-700 tracking-tight">Incident Details</h3>
            </div>
            <div className="flex-1 px-8 py-8 bg-stone-50/60">
              <div className="grid grid-cols-2 gap-x-10 mb-8">
                <LabelValue label="Date of Reporting" value={props.dateOfReporting} large />
                <LabelValue label="Incident Type" value={props.incidentType} large />
              </div>

              <div className="border-t border-stone-200 pt-6 mb-8">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-3">Incident Summary</p>
                <p className="text-[12pt] font-medium text-stone-800 leading-[1.9] bg-white rounded-lg px-6 py-5 border border-stone-200">
                  {props.incidentSummary}
                </p>
              </div>

              <div className="border-t border-stone-200 pt-6">
                <div className="flex items-center gap-1.5 mb-5">
                  {icons.mapPin}
                  <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider">Location</p>
                </div>
                <div className="grid grid-cols-2 gap-x-10 gap-y-6">
                  {props.location.roadName && (
                    <div className="col-span-2">
                      <LabelValue label="Road / Highway" value={props.location.roadName} large />
                    </div>
                  )}
                  {props.location.area && <LabelValue label="Area" value={props.location.area} large />}
                  {props.location.city && <LabelValue label="City" value={props.location.city} large />}
                  {props.location.state && <LabelValue label="State" value={props.location.state} large />}
                  {props.location.pin && <LabelValue label="PIN" value={props.location.pin} mono large />}
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white border border-stone-200 rounded-xl overflow-hidden">
            <div className="flex items-center gap-2 px-8 py-5 border-b border-stone-100 bg-white">
              <span className="w-10 h-10 rounded-lg flex items-center justify-center bg-emerald-50">{icons.checkCircle}</span>
              <h3 className="text-[16pt] font-display font-extrabold text-emerald-700 tracking-tight">Resolution Details</h3>
            </div>
            <div className="px-8 py-8 bg-stone-50/60">
              {props.resolutionOpinion && (
                <div className="mb-6">
                  <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-3">Resolution / Opinion</p>
                  <p className="text-[12pt] font-medium text-stone-800 leading-[1.9] bg-white rounded-lg px-6 py-5 border border-stone-200">
                    {props.resolutionOpinion}
                  </p>
                </div>
              )}
              <div className="border-t border-stone-200" />
            </div>
          </div>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={2} total={3} />
      </div>

      {/* ════════════ PAGE 3: CLOSURE SUMMARY ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader subtitle={sub} />

        <div className="flex-1 px-10 py-8 flex flex-col gap-6">
          <div className="bg-white border border-stone-200 rounded-xl overflow-hidden">
            <div className="flex items-center gap-2 px-8 py-5 border-b border-stone-100 bg-white">
              <span className="w-10 h-10 rounded-lg flex items-center justify-center bg-emerald-50">{icons.shield}</span>
              <h3 className="text-[16pt] font-display font-extrabold text-emerald-700 tracking-tight">Closure Summary</h3>
            </div>
            <div className="px-8 py-8 bg-stone-50/60">
              {/* Savings */}
              {(props.moneySaved || props.timeSaved) && (
                <div className="grid grid-cols-2 gap-5 mb-8">
                  {props.moneySaved && (
                    <div className="bg-emerald-50 border border-emerald-200 rounded-xl px-6 py-7 text-center">
                      <p className="text-[10pt] font-semibold text-emerald-600 uppercase tracking-wider mb-3">Money Saved</p>
                      <p className="text-[24pt] font-bold text-emerald-700">{props.moneySaved}</p>
                    </div>
                  )}
                  {props.timeSaved && (
                    <div className="bg-emerald-50 border border-emerald-200 rounded-xl px-6 py-7 text-center">
                      <p className="text-[10pt] font-semibold text-emerald-600 uppercase tracking-wider mb-3">Time Saved</p>
                      <p className="text-[24pt] font-bold text-emerald-700">{props.timeSaved}</p>
                    </div>
                  )}
                </div>
              )}

              <div className="grid grid-cols-2 gap-x-10 border-t border-stone-200 pt-6 mb-6">
                <div>
                  <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Closure Outcome</p>
                  <span className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-[11pt] font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                    <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
                    {props.closureOutcome}
                  </span>
                </div>
                <LabelValue label="Closure Date" value={props.closureDate} large />
              </div>

              <div className="grid grid-cols-3 gap-x-10 border-t border-stone-200 pt-6 mb-6">
                <LabelValue label="Duration" value={`${props.durationDays} days`} large />
                <div>
                  <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">SLA Status</p>
                  <span
                    className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg text-[11pt] font-semibold border ${
                      props.slaStatus === 'Within SLA'
                        ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                        : 'bg-red-50 text-red-700 border-red-200'
                    }`}
                  >
                    <span className={`w-2.5 h-2.5 rounded-full ${props.slaStatus === 'Within SLA' ? 'bg-emerald-500' : 'bg-red-500'}`} />
                    {props.slaStatus}
                  </span>
                </div>
                <LabelValue label="Documents Filed" value={String(props.documentsFiledCount)} large />
              </div>

              {props.closingNotes && (
                <div className="border-t border-stone-200 pt-6">
                  <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-3">Closing Notes</p>
                  <p className="text-[12pt] font-medium text-stone-800 leading-[1.9] bg-white rounded-lg px-6 py-5 border border-stone-200">
                    {props.closingNotes}
                  </p>
                </div>
              )}
            </div>
          </div>

        </div>

        <div className="px-10 pb-5">
          <p className="text-[9pt] font-bold text-stone-400 mb-1.5">Disclaimer</p>
          <p className="text-[9pt] text-stone-400 leading-relaxed">
            This is a system-generated report. The information contained herein is based on data provided by the subscriber and may not
            reflect the complete facts of the incident. For further details, please refer to our Terms &amp; Conditions.
          </p>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={3} total={3} />
      </div>
    </div>
  )
}

export type { IncidentClosureReportProps }
