interface MonthlyIncidentSummaryReportProps {
  // Cover (existing)
  subscriberId: string
  subscriberName: string
  dateGenerated: string
  reportMonth: string
  reportYear: string

  // Page 2: Incident Summary
  totalIncidents: number
  totalChallans: number
  totalCases: number
  totalRenewals: number
  incidentTypeBreakdown: Array<{ type: string; count: number }>

  // Page 3: Analytics & Aging
  topStates: Array<{ state: string; count: number }>
  topReporters: Array<{ name: string; count: number }>
  agingBuckets: {
    within15Days: number
    within15To30Days: number
    within30To60Days: number
    above60Days: number
  }

  // Page 4: Conclusion
  conclusionText: string
}

/* ── Shared sub-components ── */

function PageHeader({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="flex items-center justify-between px-10 py-4 border-b border-stone-200 bg-white">
      <img src="/lots247-logo.png" alt="LOTS247" className="h-6 w-auto" />
      <div className="text-right">
        <p className="text-[9pt] font-display font-semibold text-stone-700">{title}</p>
        <p className="text-[8pt] font-mono text-stone-400 mt-px">{subtitle}</p>
      </div>
    </div>
  )
}

function PageFooter({ page, total }: { page: number; total: number }) {
  return (
    <div className="px-10 py-3 border-t border-stone-200 bg-white flex items-center text-[8pt] text-stone-400 gap-3">
      <span>Page {page} of {total}</span>
      <span className="text-stone-300">|</span>
      <span>Generated by LOTS247</span>
    </div>
  )
}

function SectionCard({
  title,
  icon,
  iconBg = 'bg-emerald-50',
  children,
}: {
  title: string
  icon: React.ReactNode
  iconBg?: string
  children: React.ReactNode
}) {
  return (
    <div className="bg-white border border-stone-200 rounded-xl overflow-hidden">
      <div className="flex items-center gap-2 px-8 py-3 border-b border-stone-100 bg-white">
        <span className={`w-9 h-9 rounded-lg flex items-center justify-center ${iconBg}`}>{icon}</span>
        <h3 className="text-[13pt] font-display font-extrabold text-emerald-700 tracking-tight">
          {title}
        </h3>
      </div>
      <div className="px-8 py-5 bg-stone-50/60">{children}</div>
    </div>
  )
}

/* ── SVG icons (blue theme for MIS) ── */

const icons = {
  chartBar: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" />
    </svg>
  ),
  listBullet: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0ZM3.75 12h.007v.008H3.75V12Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm-.375 5.25h.007v.008H3.75v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
  ),
  mapPin: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
      <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z" />
    </svg>
  ),
  users: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M15 19.128a9.38 9.38 0 0 0 2.625.372 9.337 9.337 0 0 0 4.121-.952 4.125 4.125 0 0 0-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 0 1 8.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0 1 11.964-3.07M12 6.375a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0Zm8.25 2.25a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z" />
    </svg>
  ),
  clock: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>
  ),
  documentCheck: (
    <svg className="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M10.125 2.25h-4.5c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Zm3.75 11.625-2.625 2.625-1.125-1.125" />
    </svg>
  ),
}

/* ── Main Report (4 A4 pages) ── */

export default function MonthlyIncidentSummaryReport(
  props: MonthlyIncidentSummaryReportProps
) {
  return (
    <div
      id="monthly-incident-summary-report"
      style={{ fontFamily: '"DM Sans", system-ui, sans-serif' }}
    >
      {/* ════════════ PAGE 1: COVER ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col overflow-hidden">
        {/* Hero image with wave */}
        <div className="w-full h-[38%] flex-shrink-0">
          <img src="/report-cover-bg.png" alt="" className="w-full h-full object-cover object-top" />
        </div>

        {/* Content below wave */}
        <div className="flex-1 flex flex-col items-center px-14 text-center">
          {/* Logo */}
          <div className="pt-6 pb-4">
            <img src="/lots247-logo.png" alt="LOTS247" className="h-10 w-auto mx-auto" />
          </div>

          {/* Title */}
          <h1 className="text-[26pt] font-display font-bold text-stone-900 tracking-tight leading-tight">
            Monthly Incident
          </h1>
          <h1 className="text-[26pt] font-display font-bold text-stone-900 tracking-tight leading-tight mb-6">
            Summary
          </h1>

          {/* Period card */}
          <div className="w-full max-w-sm bg-white border border-stone-200 rounded-xl overflow-hidden mb-10">
            <div className="flex border-b border-stone-200">
              <div className="flex-1 px-6 py-5 border-r border-stone-200 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Month</p>
                <p className="text-[18pt] font-bold text-stone-900">{props.reportMonth}</p>
              </div>
              <div className="flex-1 px-6 py-5 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Year</p>
                <p className="text-[18pt] font-bold text-stone-900">{props.reportYear}</p>
              </div>
            </div>
            <div className="px-6 py-3 bg-stone-50">
              <div className="flex items-center justify-center gap-3">
                <span className="w-2.5 h-2.5 rounded-full bg-blue-500" />
                <span className="text-[11pt] font-medium text-stone-600">MIS Report</span>
              </div>
            </div>
          </div>

          {/* Details */}
          <div className="w-full max-w-sm">
            <div className="grid grid-cols-2 gap-x-12 gap-y-6 text-left">
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Subscriber</p>
                <p className="text-[14pt] font-bold text-stone-900">{props.subscriberName}</p>
                <p className="text-[10pt] font-mono text-stone-500 mt-1">{props.subscriberId}</p>
              </div>
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Date Generated</p>
                <p className="text-[14pt] font-bold text-stone-900">{props.dateGenerated}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="h-1.5 bg-emerald-600" />
        <PageFooter page={1} total={4} />
      </div>

      {/* ════════════ PAGE 2: INCIDENT SUMMARY ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Incident Summary" subtitle={`${props.reportMonth} ${props.reportYear}`} />

        <div className="flex-1 px-10 py-8 flex flex-col gap-6">
          {/* Total Incidents — full width hero card */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl px-8 py-7 text-center">
            <p className="text-[10pt] font-semibold text-blue-600 uppercase tracking-wider mb-3">Total Incidents</p>
            <p className="text-[36pt] font-bold text-blue-700">{props.totalIncidents}</p>
          </div>

          {/* 3-column grid: Challans / Cases / Renewals */}
          <div className="grid grid-cols-3 gap-5">
            <div className="bg-white border border-stone-200 rounded-xl px-6 py-6 text-center">
              <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Challans</p>
              <p className="text-[22pt] font-bold text-stone-900">{props.totalChallans}</p>
            </div>
            <div className="bg-white border border-stone-200 rounded-xl px-6 py-6 text-center">
              <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Cases</p>
              <p className="text-[22pt] font-bold text-stone-900">{props.totalCases}</p>
            </div>
            <div className="bg-white border border-stone-200 rounded-xl px-6 py-6 text-center">
              <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Renewals</p>
              <p className="text-[22pt] font-bold text-stone-900">{props.totalRenewals}</p>
            </div>
          </div>

          {/* Incident Type Breakdown */}
          <SectionCard title="Incident Type Breakdown" icon={icons.listBullet}>
            <div className="flex flex-col gap-4">
              {props.incidentTypeBreakdown.map((item, i) => (
                <div key={i} className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className="w-2.5 h-2.5 rounded-full bg-blue-500" />
                    <span className="text-[11pt] font-medium text-stone-700">{item.type}</span>
                  </div>
                  <span className="text-[12pt] font-bold text-stone-900">{item.count}</span>
                </div>
              ))}
            </div>
          </SectionCard>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={2} total={4} />
      </div>

      {/* ════════════ PAGE 3: ANALYTICS & AGING ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Incident Summary" subtitle={`${props.reportMonth} ${props.reportYear}`} />

        <div className="flex-1 px-10 py-6 flex flex-col gap-4">
          {/* Top States Breakdown */}
          <SectionCard title="Top States Breakdown" icon={icons.mapPin}>
            <div className="flex flex-col gap-2.5">
              {props.topStates.map((item, i) => (
                <div key={i} className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className="w-5 h-5 rounded-full bg-blue-100 flex items-center justify-center text-[7pt] font-bold text-blue-600">{i + 1}</span>
                    <span className="text-[10pt] font-medium text-stone-700">{item.state}</span>
                  </div>
                  <span className="text-[11pt] font-bold text-stone-900">{item.count}</span>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Top Reporters */}
          <SectionCard title="Top Reporters" icon={icons.users}>
            <div className="flex flex-col gap-2.5">
              {props.topReporters.map((item, i) => (
                <div key={i} className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className="w-5 h-5 rounded-full bg-blue-100 flex items-center justify-center text-[7pt] font-bold text-blue-600">{i + 1}</span>
                    <span className="text-[10pt] font-medium text-stone-700">{item.name}</span>
                  </div>
                  <span className="text-[11pt] font-bold text-stone-900">{item.count}</span>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Aging Time of Incidents — 2x2 grid */}
          <SectionCard title="Aging Time of Incidents" icon={icons.clock}>
            <div className="grid grid-cols-2 gap-3">
              <div className="bg-emerald-50 border border-emerald-200 rounded-lg px-4 py-3.5 text-center">
                <p className="text-[8pt] font-semibold text-emerald-600 uppercase tracking-wider mb-1">Within 15 Days</p>
                <p className="text-[18pt] font-bold text-emerald-700">{props.agingBuckets.within15Days}</p>
              </div>
              <div className="bg-blue-50 border border-blue-200 rounded-lg px-4 py-3.5 text-center">
                <p className="text-[8pt] font-semibold text-blue-600 uppercase tracking-wider mb-1">15–30 Days</p>
                <p className="text-[18pt] font-bold text-blue-700">{props.agingBuckets.within15To30Days}</p>
              </div>
              <div className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-3.5 text-center">
                <p className="text-[8pt] font-semibold text-amber-600 uppercase tracking-wider mb-1">30–60 Days</p>
                <p className="text-[18pt] font-bold text-amber-700">{props.agingBuckets.within30To60Days}</p>
              </div>
              <div className="bg-red-50 border border-red-200 rounded-lg px-4 py-3.5 text-center">
                <p className="text-[8pt] font-semibold text-red-600 uppercase tracking-wider mb-1">60+ Days</p>
                <p className="text-[18pt] font-bold text-red-700">{props.agingBuckets.above60Days}</p>
              </div>
            </div>
          </SectionCard>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={3} total={4} />
      </div>

      {/* ════════════ PAGE 4: CONCLUSION ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Incident Summary" subtitle={`${props.reportMonth} ${props.reportYear}`} />

        <div className="flex-1 px-10 py-8 flex flex-col">
          <SectionCard title="Conclusion" icon={icons.documentCheck}>
            <p className="text-[12pt] font-medium text-stone-800 leading-[1.9] bg-white rounded-lg px-6 py-5 border border-stone-200">
              {props.conclusionText}
            </p>
          </SectionCard>

          {/* Push disclaimer to bottom */}
          <div className="flex-1" />

          {/* Disclaimer */}
          <div className="pb-2">
            <p className="text-[9pt] font-bold text-stone-400 mb-1.5">Disclaimer</p>
            <p className="text-[9pt] text-stone-400 leading-relaxed">
              This is a system-generated report. The information contained herein is based on data provided by the subscriber and may not
              reflect the complete facts of the incidents. For further details, please refer to our Terms &amp; Conditions.
            </p>
          </div>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={4} total={4} />
      </div>
    </div>
  )
}

export type { MonthlyIncidentSummaryReportProps }
