interface ChallanStatusRow {
  status: string
  vehicles: number
  count: number
  amount: number
}

interface StateRow {
  state: string
  vehicles: number
  count: number
  amount: number
}

interface AmountRangeRow {
  range: string
  vehicles: number
  count: number
  amount: number
}

interface RawDataLink {
  label: string
  href: string
  vehicles: number
  challans: number
  amount: number
  tone: 'amber' | 'red' | 'blue' | 'stone'
}

interface MonthlyChallanSummaryReportProps {
  subscriberId: string
  subscriberName: string
  dateGenerated: string
  reportMonth: string
  reportYear: string

  overallStatus: ChallanStatusRow[]
  overallTotal: ChallanStatusRow

  stateWisePendingOnline: StateRow[]
  stateWisePendingOnlineTotal: StateRow

  stateWisePendingInCourt: StateRow[]
  stateWisePendingInCourtTotal: StateRow

  amountRangePendingOnline: AmountRangeRow[]
  amountRangePendingOnlineTotal: AmountRangeRow

  amountRangePendingInCourt: AmountRangeRow[]
  amountRangePendingInCourtTotal: AmountRangeRow

  rawDataLinks: RawDataLink[]
}

/* ── Shared sub-components ── */

function PageHeader({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="flex items-center justify-between px-10 py-4 border-b border-stone-200 bg-white">
      <img src="/lots247-logo.png" alt="LOTS247" className="h-6 w-auto" />
      <div className="text-right">
        <p className="text-[9pt] font-display font-semibold text-stone-700">{title}</p>
        <p className="text-[8pt] font-mono text-stone-400 mt-px">{subtitle}</p>
      </div>
    </div>
  )
}

function PageFooter({ page, total }: { page: number; total: number }) {
  return (
    <div className="px-10 py-3 border-t border-stone-200 bg-white flex items-center text-[8pt] text-stone-400 gap-3">
      <span>Page {page} of {total}</span>
      <span className="text-stone-300">|</span>
      <span>Generated by LOTS247</span>
    </div>
  )
}

function SectionTitle({ title, icon }: { title: string; icon: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2 mb-3">
      <span className="w-8 h-8 rounded-lg flex items-center justify-center bg-emerald-50">
        {icon}
      </span>
      <h3 className="text-[12pt] font-display font-extrabold text-emerald-700 tracking-tight">
        {title}
      </h3>
    </div>
  )
}

function formatINR(n: number): string {
  return `₹${n.toLocaleString('en-IN')}`
}

/* ── Tables ── */

function StatusTable({
  rows,
  total,
}: {
  rows: ChallanStatusRow[]
  total: ChallanStatusRow
}) {
  return (
    <table className="w-full text-[9.5pt] border-collapse">
      <thead>
        <tr className="bg-stone-100">
          <th className="px-3 py-2 text-left font-semibold text-stone-700 border border-stone-200">
            Challan Status
          </th>
          <th className="px-3 py-2 text-center font-semibold text-stone-700 border border-stone-200">
            Unique Vehicle Count
          </th>
          <th className="px-3 py-2 text-center font-semibold text-stone-700 border border-stone-200">
            No of Challan
          </th>
          <th className="px-3 py-2 text-right font-semibold text-stone-700 border border-stone-200">
            Challan Amount
          </th>
        </tr>
      </thead>
      <tbody>
        {rows.map((r) => (
          <tr key={r.status}>
            <td className="px-3 py-2 text-stone-800 border border-stone-200">{r.status}</td>
            <td className="px-3 py-2 text-center text-stone-800 tabular-nums border border-stone-200">{r.vehicles}</td>
            <td className="px-3 py-2 text-center text-stone-800 tabular-nums border border-stone-200">{r.count}</td>
            <td className="px-3 py-2 text-right text-stone-800 tabular-nums border border-stone-200">{formatINR(r.amount)}</td>
          </tr>
        ))}
        <tr className="bg-stone-100 font-semibold">
          <td className="px-3 py-2 border border-stone-200">Grand Total</td>
          <td className="px-3 py-2 text-center tabular-nums border border-stone-200">{total.vehicles}</td>
          <td className="px-3 py-2 text-center tabular-nums border border-stone-200">{total.count}</td>
          <td className="px-3 py-2 text-right tabular-nums border border-stone-200">{formatINR(total.amount)}</td>
        </tr>
      </tbody>
    </table>
  )
}

function StateTable({
  title,
  rows,
  total,
}: {
  title: string
  rows: StateRow[]
  total: StateRow
}) {
  return (
    <div>
      <div className="px-3 py-2 bg-emerald-50 border border-emerald-200 border-b-0 rounded-t">
        <p className="text-center text-[10pt] font-display font-bold uppercase tracking-wide text-emerald-700">
          {title}
        </p>
      </div>
      <table className="w-full text-[9pt] border-collapse">
        <thead>
          <tr className="bg-stone-50">
            <th className="px-2 py-1.5 text-left font-semibold text-stone-700 border border-stone-200">State</th>
            <th className="px-2 py-1.5 text-center font-semibold text-stone-700 border border-stone-200">Unique Vehicle Count</th>
            <th className="px-2 py-1.5 text-center font-semibold text-stone-700 border border-stone-200">No of Challan</th>
            <th className="px-2 py-1.5 text-right font-semibold text-stone-700 border border-stone-200">Challan Amount</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.state}>
              <td className="px-2 py-1.5 text-stone-800 border border-stone-200">{r.state}</td>
              <td className="px-2 py-1.5 text-center text-stone-800 tabular-nums border border-stone-200">{r.vehicles}</td>
              <td className="px-2 py-1.5 text-center text-stone-800 tabular-nums border border-stone-200">{r.count}</td>
              <td className="px-2 py-1.5 text-right text-stone-800 tabular-nums border border-stone-200">{formatINR(r.amount)}</td>
            </tr>
          ))}
          <tr className="bg-stone-100 font-semibold">
            <td className="px-2 py-1.5 border border-stone-200">Grand Total</td>
            <td className="px-2 py-1.5 text-center tabular-nums border border-stone-200">{total.vehicles}</td>
            <td className="px-2 py-1.5 text-center tabular-nums border border-stone-200">{total.count}</td>
            <td className="px-2 py-1.5 text-right tabular-nums border border-stone-200">{formatINR(total.amount)}</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}

function AmountRangeTable({
  title,
  rows,
  total,
}: {
  title: string
  rows: AmountRangeRow[]
  total: AmountRangeRow
}) {
  return (
    <div>
      <div className="px-3 py-2 bg-emerald-50 border border-emerald-200 border-b-0 rounded-t">
        <p className="text-center text-[10pt] font-display font-bold uppercase tracking-wide text-emerald-700">
          {title}
        </p>
      </div>
      <table className="w-full text-[9pt] border-collapse">
        <thead>
          <tr className="bg-stone-50">
            <th className="px-2 py-1.5 text-left font-semibold text-stone-700 border border-stone-200">Grouped Amount</th>
            <th className="px-2 py-1.5 text-center font-semibold text-stone-700 border border-stone-200">Unique Vehicle Count</th>
            <th className="px-2 py-1.5 text-center font-semibold text-stone-700 border border-stone-200">No of Challan</th>
            <th className="px-2 py-1.5 text-right font-semibold text-stone-700 border border-stone-200">Challan Amount</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.range}>
              <td className="px-2 py-1.5 text-stone-800 tabular-nums border border-stone-200">{r.range}</td>
              <td className="px-2 py-1.5 text-center text-stone-800 tabular-nums border border-stone-200">{r.vehicles}</td>
              <td className="px-2 py-1.5 text-center text-stone-800 tabular-nums border border-stone-200">{r.count}</td>
              <td className="px-2 py-1.5 text-right text-stone-800 tabular-nums border border-stone-200">{formatINR(r.amount)}</td>
            </tr>
          ))}
          <tr className="bg-stone-100 font-semibold">
            <td className="px-2 py-1.5 border border-stone-200">Grand Total</td>
            <td className="px-2 py-1.5 text-center tabular-nums border border-stone-200">{total.vehicles}</td>
            <td className="px-2 py-1.5 text-center tabular-nums border border-stone-200">{total.count}</td>
            <td className="px-2 py-1.5 text-right tabular-nums border border-stone-200">{formatINR(total.amount)}</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}

/* ── SVG icons ── */

const icons = {
  layers: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 6.878V6a2.25 2.25 0 0 1 2.25-2.25h7.5A2.25 2.25 0 0 1 18 6v.878m-12 0c.235-.083.487-.128.75-.128h10.5c.263 0 .515.045.75.128m-12 0A2.25 2.25 0 0 0 4.5 9v.878m13.5-3A2.25 2.25 0 0 1 19.5 9v.878m0 0a2.246 2.246 0 0 0-.75-.128H5.25c-.263 0-.515.045-.75.128m15 0A2.25 2.25 0 0 1 21 12v6a2.25 2.25 0 0 1-2.25 2.25H5.25A2.25 2.25 0 0 1 3 18v-6c0-.98.626-1.813 1.5-2.122" />
    </svg>
  ),
  map: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="m15 11.25 1.5 1.5.75-.75V8.758l2.276-.61a3 3 0 1 0-3.675-3.675l-.61 2.277H12l-.75.75 1.5 1.5M15 11.25l-8.47 8.47c-.34.34-.8.53-1.28.53s-.94.19-1.28.53l-.97.97-.75-.75.97-.97c.34-.34.53-.8.53-1.28s.19-.94.53-1.28L12.75 9M15 11.25 12.75 9" />
    </svg>
  ),
  rupee: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M14.121 7.629A3 3 0 0 0 9.017 9.43c-.023.212-.002.425.028.636l.506 3.541a4.5 4.5 0 0 1-.43 2.65L9 16.5l1.539-.717a4.5 4.5 0 0 1 2.65-.43l3.54.506c.211.03.424.052.636.028a3 3 0 0 0 1.80-5.105L14.12 7.629Z" />
      <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 6h9m-9 4.5h9M9 6v6.75M15 6v6.75" />
    </svg>
  ),
  database: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M20.25 6.375c0 2.278-3.694 4.125-8.25 4.125S3.75 8.653 3.75 6.375m16.5 0c0-2.278-3.694-4.125-8.25-4.125S3.75 4.097 3.75 6.375m16.5 0v11.25c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125V6.375m16.5 0v3.75m-16.5-3.75v3.75m16.5 0v3.75C20.25 16.153 16.556 18 12 18s-8.25-1.847-8.25-4.125v-3.75m16.5 0c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125" />
    </svg>
  ),
  download: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.75} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
    </svg>
  ),
}

const TONE_STYLES: Record<RawDataLink['tone'], { bg: string; border: string; text: string }> = {
  amber: { bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-700' },
  red: { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-700' },
  blue: { bg: 'bg-blue-50', border: 'border-blue-200', text: 'text-blue-700' },
  stone: { bg: 'bg-stone-50', border: 'border-stone-200', text: 'text-stone-700' },
}

/* ── Main Report (3 A4 pages) ── */

export default function MonthlyChallanSummaryReport(
  props: MonthlyChallanSummaryReportProps
) {
  const headerSubtitle = `${props.reportMonth} ${props.reportYear}`

  return (
    <div
      id="monthly-challan-summary-report"
      style={{ fontFamily: '"DM Sans", system-ui, sans-serif' }}
    >
      {/* ════════════ PAGE 1: COVER ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col overflow-hidden">
        <div className="w-full h-[38%] flex-shrink-0">
          <img src="/report-cover-bg.png" alt="" className="w-full h-full object-cover object-top" />
        </div>

        <div className="flex-1 flex flex-col items-center px-14 text-center">
          <div className="pt-6 pb-4">
            <img src="/lots247-logo.png" alt="LOTS247" className="h-10 w-auto mx-auto" />
          </div>

          <h1 className="text-[26pt] font-display font-bold text-stone-900 tracking-tight leading-tight">
            Monthly Challan
          </h1>
          <h1 className="text-[26pt] font-display font-bold text-stone-900 tracking-tight leading-tight mb-6">
            Summary
          </h1>

          <div className="w-full max-w-sm bg-white border border-stone-200 rounded-xl overflow-hidden mb-10">
            <div className="flex border-b border-stone-200">
              <div className="flex-1 px-6 py-5 border-r border-stone-200 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Month</p>
                <p className="text-[18pt] font-bold text-stone-900">{props.reportMonth}</p>
              </div>
              <div className="flex-1 px-6 py-5 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Year</p>
                <p className="text-[18pt] font-bold text-stone-900">{props.reportYear}</p>
              </div>
            </div>
            <div className="px-6 py-3 bg-stone-50">
              <div className="flex items-center justify-center gap-3">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
                <span className="text-[11pt] font-medium text-stone-600">MIS-Challan Report</span>
              </div>
            </div>
          </div>

          <div className="w-full max-w-sm">
            <div className="grid grid-cols-2 gap-x-12 gap-y-6 text-left">
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Subscriber</p>
                <p className="text-[14pt] font-bold text-stone-900">{props.subscriberName}</p>
                <p className="text-[10pt] font-mono text-stone-500 mt-1">{props.subscriberId}</p>
              </div>
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Date Generated</p>
                <p className="text-[14pt] font-bold text-stone-900">{props.dateGenerated}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="h-1.5 bg-emerald-600" />
        <PageFooter page={1} total={4} />
      </div>

      {/* ════════════ PAGE 2: OVERALL + STATE WISE ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Challan Summary" subtitle={headerSubtitle} />

        <div className="flex-1 px-10 py-6 flex flex-col gap-6">
          <div>
            <SectionTitle title="Overall Challan Status" icon={icons.layers} />
            <StatusTable rows={props.overallStatus} total={props.overallTotal} />
          </div>

          <div>
            <SectionTitle title="State Wise Challan" icon={icons.map} />
            <div className="flex flex-col gap-4">
              <StateTable
                title="Pending Online"
                rows={props.stateWisePendingOnline}
                total={props.stateWisePendingOnlineTotal}
              />
              <StateTable
                title="Pending In Court"
                rows={props.stateWisePendingInCourt}
                total={props.stateWisePendingInCourtTotal}
              />
            </div>
          </div>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={2} total={4} />
      </div>

      {/* ════════════ PAGE 3: AMOUNT RANGE ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Challan Summary" subtitle={headerSubtitle} />

        <div className="flex-1 px-10 py-6 flex flex-col gap-4">
          <SectionTitle title="Amount Range" icon={icons.rupee} />
          <div className="flex flex-col gap-4">
            <AmountRangeTable
              title="Pending Online"
              rows={props.amountRangePendingOnline}
              total={props.amountRangePendingOnlineTotal}
            />
            <AmountRangeTable
              title="Pending In Court"
              rows={props.amountRangePendingInCourt}
              total={props.amountRangePendingInCourtTotal}
            />
          </div>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={3} total={4} />
      </div>

      {/* ════════════ PAGE 4: CHALLAN RAW DATA ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Challan Summary" subtitle={headerSubtitle} />

        <div className="flex-1 px-10 py-8 flex flex-col gap-5">
          <SectionTitle title="Challan Raw Data" icon={icons.database} />

          <p className="text-[10pt] text-stone-600 leading-relaxed -mt-1">
            Download the raw challan data for each category. Files open in Microsoft Excel,
            Numbers, or Google Sheets.
          </p>

          <div className="flex flex-col gap-3">
            {props.rawDataLinks.map((link) => {
              const tone = TONE_STYLES[link.tone]
              return (
                <a
                  key={link.label}
                  href={link.href}
                  download
                  className={`group flex items-center justify-between gap-4 rounded-xl border ${tone.border} ${tone.bg} px-5 py-4 hover:brightness-95 transition-all`}
                >
                  <div className="flex items-center gap-4 min-w-0">
                    <div className="min-w-0">
                      <p className={`text-[12pt] font-display font-bold ${tone.text} leading-tight`}>
                        {link.label}
                      </p>
                      <p className="text-[9pt] text-stone-500 mt-0.5 tabular-nums">
                        {link.vehicles} vehicles · {link.challans} challans · {formatINR(link.amount)}
                      </p>
                    </div>
                  </div>

                  <span className={`inline-flex items-center gap-1.5 text-[10pt] font-semibold ${tone.text}`}>
                    {icons.download}
                    Download .xlsx
                  </span>
                </a>
              )
            })}
          </div>

          <div className="flex-1" />

          <div className="pb-2">
            <p className="text-[9pt] font-bold text-stone-400 mb-1.5">Disclaimer</p>
            <p className="text-[9pt] text-stone-400 leading-relaxed">
              This is a system-generated report. Challan data is fetched from state RTO and traffic
              department APIs and may lag the source by 24–48 hours. Excel files contain the full
              raw challan data underlying the summary tables on page 2.
            </p>
          </div>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={4} total={4} />
      </div>
    </div>
  )
}

export type { MonthlyChallanSummaryReportProps }
