interface CaseStatusRow {
  status: string
  cases: number
  vehicles: number
}

interface CaseTypeRow {
  type: string
  cases: number
  vehicles: number
  open: number
  resolved: number
}

interface StateRow {
  state: string
  cases: number
  vehicles: number
  open: number
}

interface AuthorityRow {
  authority: string
  cases: number
  vehicles: number
  open: number
}

interface RawDataLink {
  label: string
  href: string
  cases: number
  vehicles: number
  tone: 'amber' | 'red' | 'blue' | 'stone' | 'emerald'
}

interface MonthlyCasesSummaryReportProps {
  subscriberId: string
  subscriberName: string
  dateGenerated: string
  reportMonth: string
  reportYear: string

  overallStatus: CaseStatusRow[]
  overallTotal: CaseStatusRow

  caseTypeBreakdown: CaseTypeRow[]
  caseTypeTotal: CaseTypeRow

  stateWise: StateRow[]
  stateWiseTotal: StateRow

  authorityWise: AuthorityRow[]
  authorityWiseTotal: AuthorityRow

  rawDataLinks: RawDataLink[]
}

/* ── Shared sub-components ── */

function PageHeader({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="flex items-center justify-between px-10 py-4 border-b border-stone-200 bg-white">
      <img src="/lots247-logo.png" alt="LOTS247" className="h-6 w-auto" />
      <div className="text-right">
        <p className="text-[9pt] font-display font-semibold text-stone-700">{title}</p>
        <p className="text-[8pt] font-mono text-stone-400 mt-px">{subtitle}</p>
      </div>
    </div>
  )
}

function PageFooter({ page, total }: { page: number; total: number }) {
  return (
    <div className="px-10 py-3 border-t border-stone-200 bg-white flex items-center text-[8pt] text-stone-400 gap-3">
      <span>Page {page} of {total}</span>
      <span className="text-stone-300">|</span>
      <span>Generated by LOTS247</span>
    </div>
  )
}

function SectionTitle({ title, icon }: { title: string; icon: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2 mb-4">
      <span className="w-7 h-7 rounded-md flex items-center justify-center bg-emerald-50">
        {icon}
      </span>
      <h3 className="text-[16pt] font-display font-extrabold text-emerald-700 tracking-tight">
        {title}
      </h3>
    </div>
  )
}

/* ── Case status tone map (Open = red, Resolved = emerald) ── */

const STATUS_CARD_TONE: Record<
  string,
  { bg: string; border: string; label: string }
> = {
  open: { bg: 'bg-red-50', border: 'border-red-200', label: 'text-red-700' },
  'in progress': { bg: 'bg-red-50', border: 'border-red-200', label: 'text-red-700' },
  submitted: { bg: 'bg-red-50', border: 'border-red-200', label: 'text-red-700' },
  extended: { bg: 'bg-red-50', border: 'border-red-200', label: 'text-red-700' },
  'document requested': { bg: 'bg-red-50', border: 'border-red-200', label: 'text-red-700' },
  resolved: { bg: 'bg-emerald-50', border: 'border-emerald-200', label: 'text-emerald-700' },
  closed: { bg: 'bg-emerald-50', border: 'border-emerald-200', label: 'text-emerald-700' },
}

function statusCardTone(status: string) {
  return (
    STATUS_CARD_TONE[status.trim().toLowerCase()] ?? {
      bg: 'bg-stone-50',
      border: 'border-stone-200',
      label: 'text-stone-700',
    }
  )
}

function StatBlock({
  label,
  value,
  align = 'left',
}: {
  label: string
  value: string | number
  align?: 'left' | 'right'
}) {
  return (
    <div className={align === 'right' ? 'text-right' : 'text-left'}>
      <p className="text-[8.5pt] font-semibold uppercase tracking-wider text-stone-500 mb-1">
        {label}
      </p>
      <p className="text-[15pt] font-bold text-stone-900 tabular-nums leading-none">
        {value}
      </p>
    </div>
  )
}

function OverallStatusBento({
  rows,
  total,
}: {
  rows: CaseStatusRow[]
  total: CaseStatusRow
}) {
  return (
    <div className="flex flex-col gap-3">
      <div className="rounded-xl border border-blue-200 bg-blue-50 px-5 py-4">
        <p className="text-[9.5pt] font-bold uppercase tracking-wider text-blue-700 mb-3">
          Grand Total
        </p>
        <div className="grid grid-cols-2 gap-4">
          <StatBlock label="Total Cases" value={total.cases} />
          <StatBlock label="Unique Vehicles" value={total.vehicles} align="right" />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3">
        {rows.map((r) => {
          const tone = statusCardTone(r.status)
          return (
            <div
              key={r.status}
              className={`rounded-xl border ${tone.border} ${tone.bg} px-5 py-4`}
            >
              <p className={`text-[10.5pt] font-bold uppercase tracking-wide ${tone.label} mb-3`}>
                {r.status}
              </p>
              <div className="grid grid-cols-2 gap-3">
                <StatBlock label="Cases" value={r.cases} />
                <StatBlock label="Vehicles" value={r.vehicles} align="right" />
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

/* ── Tables ── */

function CaseTypeTable({
  rows,
  total,
  showTotal = true,
}: {
  rows: CaseTypeRow[]
  total: CaseTypeRow
  showTotal?: boolean
}) {
  return (
    <div className="border border-stone-200 rounded-md overflow-hidden">
      <div className="px-3 py-2 bg-blue-50 border-b border-stone-200">
        <p className="text-center text-[10pt] font-display font-bold uppercase tracking-wide text-blue-700">
          Case Type Breakdown
        </p>
      </div>
      <table className="w-full text-[10.5pt] border-separate border-spacing-0">
        <thead>
          <tr className="bg-blue-50">
            <th className="px-3 py-3 text-left font-bold text-stone-900 border-b border-stone-200">Case Type</th>
            <th className="px-3 py-3 text-center font-bold text-stone-900 border-l border-b border-stone-200">Total Cases</th>
            <th className="px-3 py-3 text-center font-bold text-stone-900 border-l border-b border-stone-200">Open</th>
            <th className="px-3 py-3 text-center font-bold text-stone-900 border-l border-b border-stone-200">Resolved</th>
            <th className="px-3 py-3 text-right font-bold text-stone-900 border-l border-b border-stone-200">Vehicles</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={r.type} className={i % 2 === 1 ? 'bg-stone-50' : ''}>
              <td className="px-3 py-3 text-stone-900 font-medium border-b border-stone-200">{r.type}</td>
              <td className="px-3 py-3 text-center text-stone-900 font-medium tabular-nums border-l border-b border-stone-200">{r.cases}</td>
              <td className="px-3 py-3 text-center text-red-700 font-medium tabular-nums border-l border-b border-stone-200">{r.open}</td>
              <td className="px-3 py-3 text-center text-emerald-700 font-medium tabular-nums border-l border-b border-stone-200">{r.resolved}</td>
              <td className="px-3 py-3 text-right text-stone-900 font-medium tabular-nums border-l border-b border-stone-200">{r.vehicles}</td>
            </tr>
          ))}
          {showTotal && (
            <tr className="font-bold bg-blue-50">
              <td className="px-3 py-3 text-stone-900">Grand Total</td>
              <td className="px-3 py-3 text-center tabular-nums text-stone-900 border-l border-stone-200">{total.cases}</td>
              <td className="px-3 py-3 text-center tabular-nums text-red-700 border-l border-stone-200">{total.open}</td>
              <td className="px-3 py-3 text-center tabular-nums text-emerald-700 border-l border-stone-200">{total.resolved}</td>
              <td className="px-3 py-3 text-right tabular-nums text-stone-900 border-l border-stone-200">{total.vehicles}</td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  )
}

function StateTable({
  rows,
  total,
  showTotal = true,
}: {
  rows: StateRow[]
  total: StateRow
  showTotal?: boolean
}) {
  return (
    <div className="border border-stone-200 rounded-md overflow-hidden">
      <div className="px-3 py-2 bg-blue-50 border-b border-stone-200">
        <p className="text-center text-[10pt] font-display font-bold uppercase tracking-wide text-blue-700">
          State Wise Cases
        </p>
      </div>
      <table className="w-full text-[10.5pt] border-separate border-spacing-0">
        <thead>
          <tr className="bg-blue-50">
            <th className="px-3 py-3 text-left font-bold text-stone-900 border-b border-stone-200">State</th>
            <th className="px-3 py-3 text-center font-bold text-stone-900 border-l border-b border-stone-200">Total Cases</th>
            <th className="px-3 py-3 text-center font-bold text-stone-900 border-l border-b border-stone-200">Open</th>
            <th className="px-3 py-3 text-right font-bold text-stone-900 border-l border-b border-stone-200">Vehicles</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={r.state} className={i % 2 === 1 ? 'bg-stone-50' : ''}>
              <td className="px-3 py-3 text-stone-900 font-medium border-b border-stone-200">{r.state}</td>
              <td className="px-3 py-3 text-center text-stone-900 font-medium tabular-nums border-l border-b border-stone-200">{r.cases}</td>
              <td className="px-3 py-3 text-center text-red-700 font-medium tabular-nums border-l border-b border-stone-200">{r.open}</td>
              <td className="px-3 py-3 text-right text-stone-900 font-medium tabular-nums border-l border-b border-stone-200">{r.vehicles}</td>
            </tr>
          ))}
          {showTotal && (
            <tr className="font-bold bg-blue-50">
              <td className="px-3 py-3 text-stone-900">Grand Total</td>
              <td className="px-3 py-3 text-center tabular-nums text-stone-900 border-l border-stone-200">{total.cases}</td>
              <td className="px-3 py-3 text-center tabular-nums text-red-700 border-l border-stone-200">{total.open}</td>
              <td className="px-3 py-3 text-right tabular-nums text-stone-900 border-l border-stone-200">{total.vehicles}</td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  )
}

function AuthorityTable({
  rows,
  total,
  showTotal = true,
}: {
  rows: AuthorityRow[]
  total: AuthorityRow
  showTotal?: boolean
}) {
  return (
    <div className="border border-stone-200 rounded-md overflow-hidden">
      <div className="px-3 py-2 bg-blue-50 border-b border-stone-200">
        <p className="text-center text-[10pt] font-display font-bold uppercase tracking-wide text-blue-700">
          Authority Wise Cases
        </p>
      </div>
      <table className="w-full text-[10.5pt] border-separate border-spacing-0">
        <thead>
          <tr className="bg-blue-50">
            <th className="px-3 py-3 text-left font-bold text-stone-900 border-b border-stone-200">Authority</th>
            <th className="px-3 py-3 text-center font-bold text-stone-900 border-l border-b border-stone-200">Total Cases</th>
            <th className="px-3 py-3 text-center font-bold text-stone-900 border-l border-b border-stone-200">Open</th>
            <th className="px-3 py-3 text-right font-bold text-stone-900 border-l border-b border-stone-200">Vehicles</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={r.authority} className={i % 2 === 1 ? 'bg-stone-50' : ''}>
              <td className="px-3 py-3 text-stone-900 font-medium border-b border-stone-200">{r.authority}</td>
              <td className="px-3 py-3 text-center text-stone-900 font-medium tabular-nums border-l border-b border-stone-200">{r.cases}</td>
              <td className="px-3 py-3 text-center text-red-700 font-medium tabular-nums border-l border-b border-stone-200">{r.open}</td>
              <td className="px-3 py-3 text-right text-stone-900 font-medium tabular-nums border-l border-b border-stone-200">{r.vehicles}</td>
            </tr>
          ))}
          {showTotal && (
            <tr className="font-bold bg-blue-50">
              <td className="px-3 py-3 text-stone-900">Grand Total</td>
              <td className="px-3 py-3 text-center tabular-nums text-stone-900 border-l border-stone-200">{total.cases}</td>
              <td className="px-3 py-3 text-center tabular-nums text-red-700 border-l border-stone-200">{total.open}</td>
              <td className="px-3 py-3 text-right tabular-nums text-stone-900 border-l border-stone-200">{total.vehicles}</td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  )
}

/* ── SVG icons ── */

const icons = {
  layers: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 6.878V6a2.25 2.25 0 0 1 2.25-2.25h7.5A2.25 2.25 0 0 1 18 6v.878m-12 0c.235-.083.487-.128.75-.128h10.5c.263 0 .515.045.75.128m-12 0A2.25 2.25 0 0 0 4.5 9v.878m13.5-3A2.25 2.25 0 0 1 19.5 9v.878m0 0a2.246 2.246 0 0 0-.75-.128H5.25c-.263 0-.515.045-.75.128m15 0A2.25 2.25 0 0 1 21 12v6a2.25 2.25 0 0 1-2.25 2.25H5.25A2.25 2.25 0 0 1 3 18v-6c0-.98.626-1.813 1.5-2.122" />
    </svg>
  ),
  folder: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12.75V12A2.25 2.25 0 0 1 4.5 9.75h15A2.25 2.25 0 0 1 21.75 12v.75m-8.69-6.44-2.12-2.12a1.5 1.5 0 0 0-1.061-.44H4.5A2.25 2.25 0 0 0 2.25 6v12a2.25 2.25 0 0 0 2.25 2.25h15A2.25 2.25 0 0 0 21.75 18V9a2.25 2.25 0 0 0-2.25-2.25h-5.379a1.5 1.5 0 0 1-1.06-.44Z" />
    </svg>
  ),
  map: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="m15 11.25 1.5 1.5.75-.75V8.758l2.276-.61a3 3 0 1 0-3.675-3.675l-.61 2.277H12l-.75.75 1.5 1.5M15 11.25l-8.47 8.47c-.34.34-.8.53-1.28.53s-.94.19-1.28.53l-.97.97-.75-.75.97-.97c.34-.34.53-.8.53-1.28s.19-.94.53-1.28L12.75 9M15 11.25 12.75 9" />
    </svg>
  ),
  building: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 21h19.5m-18-18v18m10.5-18v18m6-13.5V21M6.75 6.75h.75m-.75 3h.75m-.75 3h.75m3-6h.75m-.75 3h.75m-.75 3h.75M6.75 21v-3.375c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21M3 3h12m-.75 4.5H21m-3.75 3.75h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Z" />
    </svg>
  ),
  database: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M20.25 6.375c0 2.278-3.694 4.125-8.25 4.125S3.75 8.653 3.75 6.375m16.5 0c0-2.278-3.694-4.125-8.25-4.125S3.75 4.097 3.75 6.375m16.5 0v11.25c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125V6.375m16.5 0v3.75m-16.5-3.75v3.75m16.5 0v3.75C20.25 16.153 16.556 18 12 18s-8.25-1.847-8.25-4.125v-3.75m16.5 0c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125" />
    </svg>
  ),
  download: (
    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={1.75} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
    </svg>
  ),
}

const TONE_STYLES: Record<RawDataLink['tone'], { bg: string; border: string; text: string }> = {
  amber: { bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-700' },
  red: { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-700' },
  blue: { bg: 'bg-blue-50', border: 'border-blue-200', text: 'text-blue-700' },
  stone: { bg: 'bg-stone-50', border: 'border-stone-200', text: 'text-stone-700' },
  emerald: { bg: 'bg-emerald-50', border: 'border-emerald-200', text: 'text-emerald-700' },
}

/* ── Main Report ── */

export default function MonthlyCasesSummaryReport(
  props: MonthlyCasesSummaryReportProps,
) {
  const headerSubtitle = `${props.reportMonth} ${props.reportYear}`

  const openRows = props.overallStatus.filter(
    (r) => !['resolved', 'closed'].includes(r.status.trim().toLowerCase()),
  )
  const openTotalCount = openRows.reduce((sum, r) => sum + r.cases, 0)

  return (
    <div
      id="monthly-cases-summary-report"
      style={{ fontFamily: '"DM Sans", system-ui, sans-serif' }}
    >
      {/* ════════════ PAGE 1: COVER ════════════ */}
      <div className="report-page w-[210mm] h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col overflow-hidden">
        <div className="w-full h-[24%] flex-shrink-0 overflow-hidden">
          <img src="/report-cover-bg.png" alt="" className="w-full h-full object-cover object-bottom" />
        </div>

        <div className="flex-1 flex flex-col items-center px-14 text-center">
          <div className="pt-7 pb-6">
            <img src="/lots247-logo.png" alt="LOTS247" className="h-16 w-auto mx-auto" />
          </div>

          <h1 className="text-[34pt] font-display font-bold text-stone-900 tracking-tight leading-[1.05]">
            Monthly Incident
          </h1>
          <h1 className="text-[34pt] font-display font-bold text-stone-900 tracking-tight leading-[1.05]">
            Summary
          </h1>
          <p className="text-[12pt] font-medium text-stone-500 mt-2 mb-10">
            (Cases and RTO)
          </p>

          <div className="w-full max-w-sm bg-white border border-stone-200 rounded-xl overflow-hidden mb-9">
            <div className="flex">
              <div className="flex-1 px-6 py-3.5 border-r border-stone-200 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Month</p>
                <p className="text-[17pt] font-bold text-stone-900">{props.reportMonth}</p>
              </div>
              <div className="flex-1 px-6 py-3.5 text-center">
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-1.5">Year</p>
                <p className="text-[17pt] font-bold text-stone-900">{props.reportYear}</p>
              </div>
            </div>
          </div>

          <div className="w-full max-w-md bg-stone-50 border border-stone-200 rounded-xl px-7 py-5 mb-9 text-left">
            <p className="text-[15pt] font-display font-bold text-stone-900 capitalize mb-4">
              This report covers
            </p>
            <ul className="flex flex-col gap-3">
              {[
                'Overall case status — open, in progress & resolved',
                'Case type breakdown across accidents, theft, RTO & more',
                'State-wise and authority-wise case distribution',
                'Downloadable raw case data (Excel)',
              ].map((item) => (
                <li key={item} className="flex items-center gap-3">
                  <svg
                    className="w-5 h-5 text-emerald-600 flex-shrink-0"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth={1.75}
                    viewBox="0 0 24 24"
                  >
                    <circle cx="12" cy="12" r="9.5" />
                    <path strokeLinecap="round" strokeLinejoin="round" d="m8.5 12 2.5 2.5 4.5-5" />
                  </svg>
                  <span className="text-[10.5pt] font-semibold text-stone-900 leading-snug capitalize">
                    {item}
                  </span>
                </li>
              ))}
            </ul>
          </div>

          <div className="w-full max-w-md">
            <div className="grid grid-cols-2 gap-x-12 gap-y-6 text-left">
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Subscriber</p>
                <p className="text-[14pt] font-bold text-stone-900">{props.subscriberName}</p>
                <p className="text-[10pt] font-mono text-stone-500 mt-1">{props.subscriberId}</p>
              </div>
              <div>
                <p className="text-[9pt] font-semibold text-stone-400 uppercase tracking-wider mb-2">Date Generated</p>
                <p className="text-[14pt] font-bold text-stone-900">{props.dateGenerated}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="h-1.5 bg-emerald-600" />
        <PageFooter page={1} total={4} />
      </div>

      {/* ════════════ PAGE 2: OVERALL + CASE TYPE ════════════ */}
      <div className="report-page report-page--flow w-[210mm] min-h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Incident Summary" subtitle={headerSubtitle} />

        <div className="px-10 py-6 flex flex-col gap-7">
          <div>
            <SectionTitle title="Overall Case Status" icon={icons.layers} />
            <p className="text-[10.5pt] text-stone-700 leading-[1.75] mb-5">
              This report summarises every case & RTO incident logged across fleet during{' '}
              <span className="font-bold text-stone-900">
                {props.reportMonth} {props.reportYear}
              </span>
              . A total of{' '}
              <span className="font-bold text-stone-900">{props.overallTotal.cases}</span> cases were opened across{' '}
              <span className="font-bold text-stone-900">{props.overallTotal.vehicles}</span> vehicles. Of these,{' '}
              <span className="font-bold text-red-700">
                {openTotalCount} cases are still open
              </span>{' '}
              and require active follow-up to reach resolution.
            </p>
            <OverallStatusBento rows={props.overallStatus} total={props.overallTotal} />
          </div>

          <div>
            <SectionTitle title="Case Type Breakdown" icon={icons.folder} />
            <CaseTypeTable rows={props.caseTypeBreakdown} total={props.caseTypeTotal} />
          </div>
        </div>

        <div className="mt-auto h-0.5 bg-emerald-600" />
        <PageFooter page={2} total={4} />
      </div>

      {/* ════════════ PAGE 3: STATE + AUTHORITY ════════════ */}
      <div className="report-page report-page--flow w-[210mm] min-h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Incident Summary" subtitle={headerSubtitle} />

        <div className="px-10 py-6 flex flex-col gap-7">
          <div>
            <SectionTitle title="State Wise Cases" icon={icons.map} />
            <StateTable rows={props.stateWise} total={props.stateWiseTotal} />
          </div>

          <div>
            <SectionTitle title="Authority Wise Cases" icon={icons.building} />
            <AuthorityTable rows={props.authorityWise} total={props.authorityWiseTotal} />
          </div>
        </div>

        <div className="mt-auto h-0.5 bg-emerald-600" />
        <PageFooter page={3} total={4} />
      </div>

      {/* ════════════ PAGE 4: RAW DATA ════════════ */}
      <div className="report-page report-page--flow w-[210mm] min-h-[297mm] mx-auto bg-white text-stone-900 font-sans print:shadow-none shadow-lg flex flex-col mt-8 print:mt-0">
        <PageHeader title="Monthly Incident Summary" subtitle={headerSubtitle} />

        <div className="px-10 py-8 flex flex-col gap-5">
          <SectionTitle title="Cases Raw Data" icon={icons.database} />

          <p className="text-[10pt] text-stone-600 leading-relaxed -mt-1">
            Download the raw case data for each category. Files open in Microsoft Excel,
            Numbers, or Google Sheets.
          </p>

          <div className="flex flex-col gap-3">
            {props.rawDataLinks.map((link) => {
              const tone = TONE_STYLES[link.tone]
              return (
                <a
                  key={link.label}
                  href={link.href}
                  download
                  className={`group flex items-center justify-between gap-4 rounded-xl border ${tone.border} ${tone.bg} px-5 py-4 hover:brightness-95 transition-all`}
                >
                  <div className="flex items-center gap-4 min-w-0">
                    <div className="min-w-0">
                      <p className={`text-[12pt] font-display font-bold ${tone.text} leading-tight`}>
                        {link.label}
                      </p>
                      <p className="text-[9pt] text-stone-500 mt-0.5 tabular-nums">
                        {link.vehicles} vehicles · {link.cases} cases
                      </p>
                    </div>
                  </div>

                  <span className={`inline-flex items-center gap-1.5 text-[10pt] font-semibold ${tone.text}`}>
                    {icons.download}
                    Download .xlsx
                  </span>
                </a>
              )
            })}
          </div>
        </div>

        <div className="mt-auto px-10 pb-3">
          <p className="text-[9pt] font-bold text-stone-400 mb-1.5">Disclaimer</p>
          <p className="text-[9pt] text-stone-400 leading-relaxed">
            This is a system-generated report. Case data is captured through the LOTS247 case
            management pipeline and may lag active field updates by a short window. Excel files
            contain the full raw case data underlying the summary tables in this report.
          </p>
        </div>

        <div className="h-0.5 bg-emerald-600" />
        <PageFooter page={4} total={4} />
      </div>
    </div>
  )
}

export type { MonthlyCasesSummaryReportProps }
